### ISSUE TITLE
Instantiating all exchanges at once

### ISSUE THREAD

**Issue by tych777** [ccxt-dev/ccxt#248]
Is there a way to Instantiate all exchanges at once in python 3?

**Comment by kroitor** [comment]
Hi!

Sure! Though, it depends on what you mean "to instantiate"... If you just need to create the instances, you can go ahead and do the following, as you would usually do with python disregarding whether it's sync or async: 

```Python
import ccxt.async as ccxt

exchanges = {}  # a placeholder for your instances

for id in ccxt.exchanges:
    exchange = getattr(ccxt, id)
    exchanges[id] = exchange()
```

Or, perhaps, you mean some specific type of action upon instantiation? If you mean preloading all markets, you don't have to do that, it's done automatically in background upon your first call to any method of the unified API. 

So, you basically need to instantiate them like shown above, and off you go. Also note, that some exchanges (like _1broker and xbtce) require API keys for using their public API as well. 

Let us know if that answered your question or not.

**Comment by dservais** [comment]
Dear @Kroitor, with the code you published just above, how could you collect last trade for each exchange as an example ?

**Comment by tych777** [comment]
After running the code you provided, when I run

asyncio.get_event_loop().run_until_complete(bittrex.fetch_order_book(market = 'ETH/BTC'))

I get

NameError: name 'bittrex' is not defined.

ccxt.exchanges gives me a list with class names like this
['_1broker', '_1btcxe',..., 'zaif']
, right?

I can instantiate each exchange one by one
 
_1broker=ccxt._1broker()
_1btcxe=ccxt._1btcxe()
................................
zaif=ccxt.zaif()

I'd like to be able to instantiate all exchanges at once, instead of typing for each exchange.

**Comment by kroitor** [comment]
@dservais

> how could you collect last trade for each exchange as an example ?

It depends on what you mean under *"last trade for each exchange"*. There's no such thing as a trade per exchange. Trades are per symbol. So you will have to specify a symbol at least. But not all symbols are present for all exchanges, so it really isn't so obvious, what you want to do with all exchanges and all symbols. It's all described in [the Manual](https://github.com/ccxt-dev/ccxt/wiki/Manual). Also see the [Examples here](https://github.com/ccxt-dev/ccxt/tree/master/examples).

@tych777 

Try this:

```Python
import ccxt.async as ccxt

exchanges = {}  # a placeholder for your instances

for id in ccxt.exchanges:
    exchange = getattr(ccxt, id)
    exchanges[id] = exchange()

# After running the code you provided, when I run ... 
asyncio.get_event_loop().run_until_complete(exchanges['bittrex'].fetch_order_book('ETH/BTC'))
```

So, you need to learn a little more Python to be able to do that, because your question isn't really related to the usage of the library, instead you're asking how to code in Python properly. If you don't mind I'll close this issue for now. Feel free to reopen it, or just let us know if you have any further questions with it.

**Comment by tych777** [comment]
@kroitor Thank you for this amazing project. Just missed that part.

**Comment by kroitor** [comment]
@tych777 a shorter snippet for you:

```Python
import ccxt.async as ccxt
import asyncio
asyncio.get_event_loop().run_until_complete(ccxt.bittrex().fetch_order_book('ETH/BTC'))
```

You don't need to pre-instantiate them if you just need one ticker. Thx for your feedback, we'll be happy to help if you have difficulties with it.

**Comment by nettemsarath** [comment]
could u please tell me how to instantiate all exchanges at once using Nodejs

**Comment by kroitor** [comment]
@nettemsarath https://github.com/ccxt/ccxt/blob/master/examples/js/instantiate-all-at-once.js
