### ISSUE TITLE
Fetch_order_book for all symbols python

### ISSUE THREAD

**Issue by tych777** [ccxt-dev/ccxt#262]
How to get all orderbooks from certain exchanges effectively?
I'm having trouble getting orderbooks of all symbols of a particular exchange. For some exchanges fetch_order_book('all') gives an empty dict
{'asks': [],
 'bids': [],
 'datetime': '2017-10-02T23:15:40.000Z',
 'timestamp': 1506986140273}
even though I'm able to get all orderbooks from that exchanges using their own wrappers.

For some exchanges fetch_order_book('all') gives TypeError: string indices must be integers.

What is the right way to do my task?

**Comment by kroitor** [comment]
Hi!

Currently, we don't have a single method for fetching all orderbooks at once, because it's not very frequently needed in real trading. We don't have support for 'all', you will have to:
1. Read the usage [Manual](https://github.com/ccxt-dev/ccxt/wiki/Manual) to find out what is supported or not.
2. Use symbols with fetch_order_book only.
3. Pass additional overrides with the extra params (like described in the manual).
4. Optionally use their custom API from ccxt if you know particular exchanges that offer all order books.

You will have to fetch all order books for all symbols one by one. Let us know if it answers your question or not. Thx!

**Comment by tych777** [comment]
Thank you so much. I'll dig further.

**Comment by kroitor** [comment]
@tych777 you can also check this example:
- https://github.com/ccxt-dev/ccxt/blob/master/examples/py/tickers.py
It's for the tickers, but you can switch it easily to fetch order books one by one in a loop. You can also rewrite it to loop through all symbols and fetch them all as well. I'm closing this for now if you don't mind.
