### ISSUE TITLE
CEX.io fetch_order() is not implemented yet

### ISSUE THREAD

**Issue by evgen-y2k** [ccxt-dev/ccxt#275]
Hello!
In the general class all function based on "fetch_order" is not implemented and not working. What happen? Why?
Below code example from class Exchange(object):

    def fetch_order(self, id, symbol=None, params={}):
        raise NotSupported(self.id + ' fetch_order() is not implemented yet')

    def fetchOrder(self, id, symbol=None, params={}):
        return self.fetch_order(id, symbol, params)

    def fetch_orders(self, symbol=None, params={}):
        raise NotSupported(self.id + ' fetch_orders() is not implemented yet')

    def fetchOrders(self, symbol=None, params={}):
        return self.fetch_orders(symbol, params)

**Comment by kroitor** [comment]
@evgen-y2k Hi!

Please, read this on how this library is structured and separated in base / derived classes:
https://github.com/ccxt-dev/ccxt/wiki/Manual#overview

> The ccxt library is a collection of available crypto exchanges or exchange classes. Each class implements the public and private API for a particular crypto exchange. All exchanges are derived from the base Exchange class and share a set of common methods. To access a particular exchange from ccxt library you need to create an instance of corresponding exchange class. Supported exchanges are updated frequently and new exchanges are added regularly.

This doc might also be helpful: https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md#what-you-need-to-know

So, what you look at, is not the actual implementation of fetch_order. The fetch_order is implemented for many exchanges, but not unified for all of them yet. We will be thankful if you help us with that, like many other users do. Here's the history of commits on that:
https://github.com/ccxt-dev/ccxt/search?utf8=%E2%9C%93&q=fetchOrder&type=Commits
https://github.com/ccxt-dev/ccxt/search?utf8=%E2%9C%93&q=fetchOrders&type=Commits
https://github.com/ccxt-dev/ccxt/search?utf8=%E2%9C%93&q=fetchOpenOrders&type=Commits
https://github.com/ccxt-dev/ccxt/search?q=fetchOpenOrders&type=Commits&utf8=%E2%9C%93

And the default base implementation in any base class and practically any OOP language is usually made "pure abstract", so that users are **required** to redefine the inherited methods in order for it to work. But you should not use the base Exchange class for anything except integrating a new Exchange. If you just want to use the library, you simply instantiate a class of a particular Exchange and go on. If you find some method not working or missing, you can implement it yourself and submit a pull request, or you can open an issue and maybe we or some of our contributors will implement it quickly.

<img width="1078" alt="screen shot 2017-10-06 at 18 23 25" src="https://user-images.githubusercontent.com/1294454/31285276-9750a6ce-aac3-11e7-8f59-b2b8b0a8a395.png">

Let us know if the above answers your question, thx!

**Comment by kroitor** [comment]
@evgen-y2k Oh, btw, Poloniex does not have a method for fetching an order at all, check this out: https://github.com/ccxt-dev/ccxt/pull/102 (we had to emulate it, and that is not the only exchange that doesn't have the most rudimentary tools...)

**Comment by kroitor** [comment]
https://github.com/ccxt-dev/ccxt/issues/71

**Comment by evgen-y2k** [comment]
Sorry, I wrote message before check all sources. I need working function fetch_order for CEX. Regarding poloniex I made this (it is NOT ccxt):
`def CheckOrder(orderNum):
    AllOrders = polo.returnOpenOrders(PAIR)
    if 'error' in AllOrders:
        sleep(10)
        HasOrder = CheckOrder(orderNum)
    else:
        HasOrder = False
        for i in AllOrders:
            if int(i['orderNumber']) == int(orderNum):
                HasOrder = True
                break
    return HasOrder`

**Comment by kroitor** [comment]
@evgen-y2k no problem ) I'll try to implement fetch_order for the CEX.io asap

**Comment by kroitor** [comment]
@evgen-y2k oh, one more thing: you can actually fetch orders from CEX.io with ccxt already right now! ) Just use their private API call like this:
```Python
import ccxt
cex = ccxt.cex ({ 
    # your api keys as written in the manual
})
print(cex.private_post_get_order ({
    'id': id,  # id of your order
}))
```

Let us know if it helps! Thx!

**Comment by evgen-y2k** [comment]
Thank you! It is work correctly and enought for me.

**Comment by kroitor** [comment]
@evgen-y2k thanks for reporting back! We hope to deliver even more soon! Would you mind if I close this for now? Feel free to reopen it or ask questions, if any )

**Comment by evgen-y2k** [comment]
Of course! My problem resolved. You can close ticket.
