### ISSUE TITLE
Kraken error (in limit buy)

### ISSUE THREAD

**Issue by werewere** [ccxt-dev/ccxt#290]
Hi, I'm getting an error buying in kraken (I'm doing exactly the same in other three exchanges and I'm not getting this error message). The order is executed correctly anyway, but the message says that there is an error somewhere. The python code is as follows:
```
myOrder=exchange.createLimitSellOrder ("ETH/BTC", 0.99695737, 0.06760)
print myOrder
```
And the result:

`{'info': {u'result': {u'descr': {u'order': u'sell 0.99695737 ETHXBT @ limit 0.06760'}, u'txid': [u'OW7ORX-D333N-OHF7X2']}, u'error': []}, 'id': u'OW7ORX-D333N-OHF7X2'}
`

I searched in the Issues in github but I didn't found this problem. May be this is a Kraken problem? :? The order is executed, but as it says error... I don't know, playing with money I don't like errors! ;D

**Comment by kroitor** [comment]
@werewere, but you got a correct result and you have successfully placed your order! ) There is no error (no error message in your output). Don't get confused by an **empty** `error: []` list. Empty error list == no errors. That's just how Kraken replies. Use pprint instead of print for pretty formatting to avoid confusion. Let me reformat your output for you to see, that there was no error:

```Python
{
    'info': {
        u'result': {
            u'descr': {
                u'order': u'sell 0.99695737 ETHXBT @ limit 0.06760'
            }, 
            u'txid': [u'OW7ORX-D333N-OHF7X2']
        }, 
        u'error': []  # ← no error here!
    }, 
    'id': u'OW7ORX-D333N-OHF7X2'
}
```

You can completely ignore the `info` field and use the id of the order for your tasks, the order was successful (you can verify that on Kraken website in your order history).

**Comment by werewere** [comment]
Oh, ok, thanks, I was confused! So the message is ok, perfect then.

I wonder if there is some forum or something like that so we, the users, could talk about the library and so on. In that way we wouldn't bother you (the developers) with this messages that are not really bugs. 

I've been developing software for many years, and your responsiveness is truly over the top. This is really such an amazing project Igor, thanks!

**Comment by kroitor** [comment]
@werewere thx for your feedback!

We currently don't have a forum (our website is under development right now), but it will be available at ccxt.trade soon. In the meantime, you can join our gitter chatroom here: 

[![Gitter](https://badges.gitter.im/ccxt-dev/ccxt.svg)](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

But some issues may still be worth it for other newcoming users, that's why we prefer to resolve them on GitHub for transparency.
