### ISSUE TITLE
Poloniex returns error... but the amount is ok

### ISSUE THREAD

**Issue by werewere** [ccxt-dev/ccxt#295]
Hello, I'm getting this error:

```
Traceback (most recent call last):
  File "bot.py", line 174, in <module>
    myOrder=polo.createLimitSellOrder ("ETH/BTC", 0.001566 , 0.06126141) 
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 917, in createLimitSellOrder
    return self.create_limit_sell_order(symbol, *args)
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 905, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/Library/Python/2.7/site-packages/ccxt/exchanges.py", line 16067, in create_order
    }, params))
  File "/Library/Python/2.7/site-packages/ccxt/exchanges.py", line 16134, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 228, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 266, in fetch
    self.handle_rest_errors(e, e.code, text, url, method)
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 314, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else str(http_status_code), details)
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 213, in raise_error
    details,
ccxt.errors.ExchangeNotAvailable: poloniex POST https://poloniex.com/tradingApi 422   {"error":"Total must be at least 0.0001."}

```
So, as you can see, I'm trying to sell 0.001566 ETH, but Poloniex says that I'm trying to sell less than 0.0001. I guess that this is a Poloniex problem, but as it is breaking the program, I wonder if something like a workaround could be done in ccxt, something like return an error and not an exception (to let the program continue with the execution).

It could be also some kind of transformation of the values that happens inside ccxt, I don't know

**Comment by kroitor** [comment]
@werewere hi!

Poloniex says: *Total must be at least 0.0001*

Now, let's see: `total = price * amount`

So: 

```0.001566 * 0.06126141 = 0.00009593536 ← this total value is less than 0.0001```

>  I guess that this is a Poloniex problem, but as it is breaking the program, I wonder if something like a workaround could be done in ccxt, 

> something like return an error and not an exception (to let the program continue with the execution).

The usual flow for most of coders is to use the try/except block, to catch exceptions and continue execution normally (retrying later or whatever is desired for normal execution). Browse through [examples/py](https://github.com/ccxt-dev/ccxt/tree/master/examples/py) to learn how to use exceptions with ccxt, or google for *"python exceptions tutorial"*, because this is a question again comes from a lack of basic programming skills. 

My advice is: you should learn Python first, and only when you know it very well, only after that you should try it for algorithmic trading. You could, theoretically, learn by trying to use ccxt for your needs, but if you don't understand your programming language completely, some concepts may be confusing to you. Exceptions are very useful and common, they give much more control over the execution flow than returned error values, and exceptions are easily handled if you know how to use them properly (they even have special syntax for convenience in most of languages).

**Comment by werewere** [comment]
Oh, I thought that "total" was referred to the amount, not the multiplication amount*price, now I see the problem. Absolutely true, I made the wrong order.

Yup, I have worked with exceptions, but I always prefer return values to control my code, the code seems more clean to my eyes. I think it is just my preference :)  I'm mainly a C programmer so you're right, I'm learning python while I do things for algorithmic trading... I guess I prefer to do things "on the wild".

Thanks a lot for your help!

**Comment by kroitor** [comment]
> I have worked with exceptions, but I always prefer return values to control my code, the code seems more clean to my eyes. I think it is just my preference :)

This is exactly what most of C coders say when they start learning exceptions ) I though the same a while ago ) But still, think this way: why would people invent them? My guess is: because in some cases they may actually be more useful than error values that existed previously. You've chosen an OOP language to learn, and the concept of *exception* is built into its core fundamentals. Getting used to them is just a matter of practice. Some people out there even build fortune corporations *based on exceptions*, lol...
