### ISSUE TITLE
liqui: fetchOpenOrders(): race condition 

### ISSUE THREAD

**Issue by mkutny** [ccxt-dev/ccxt#304]
I think that I ran into a race condition but cannot really nail it down.

The version is 1.9.94.

What I get is:
```
[EXCEPTION] Cannot read property '83009639' of undefined

    at parseOrder     node_modules/ccxt/ccxt.js:15981    amount = this.order[id]['amount'];
    at parseOrders    node_modules/ccxt/ccxt.js:16018    result.push (this.parseOrder (extended, market));
    at fetchOrders    node_modules/ccxt/ccxt.js:16040    let openOrders = this.parseOrders (response['return'], market);
    at _tickCallback  internal/process/next_tick.js:188
```

I'm currently experimenting with a reactive approach trying to abstract REST as if it were emitting events like WS. So I set several timers and call `ccxt` API when they fire.

So this race happens when I `createLimitOrder()` (in this case #83009639), then `fetchOpenOrders()` and at the same time, the order gets executed. The whole sequence of events is realized quite promptly, literally in a second.

It might be because my experiment effectively interleaves `ccxt` calls intruding in-between async functions. Or I see that you keep a cache of open orders and it might be caused by cache going out of sync due to purely fast order execution (unrelated to my experiment).

The problem is, the logic behind caching is quite vague for me so I can't figure out where the problem is just by looking at the code.

**Comment by kroitor** [comment]
Hi, @mkutny !

> The problem is, the logic behind caching is quite vague for me so I can't figure out where the problem is just by looking at the code.

Well, that logic can be put like so:
1. Liqui can only serve open orders or a single order
2. When an order is places it gets stored into a `this.orders` property under its id.
3. Upon any call to fetch_orders, fetch_open_orders or fetch_closed_orders, we *fetch open orders*. only, and then merge the fetched open orders that we received with the cache in the following manner: for each order from the cache, if the order is present in *open orders*, we update it as an open order, and if it isn't present in the list of open orders – we consider it closed from that moment on (and we set the status of the order to "closed" if it isn't in the open orders).
4. So, upon any call, we first merge open orders with the existing cache, updating their statuses in background, and then we filter the cache to return *open / closed* orders from the updated cache.

Does this clarify it?

+ I noticed a bug there, that is causing your error, it is caused by a typo, the line 15981 should read: `amount = this.orders[id]['amount']`, whereas `this.order[id]` is an error (no such property). This is fixed in the latest version 1.9.95+ (a new build is coming up in approx 5 minutes).

**Comment by kroitor** [comment]
@mkutny you can also try to use the built-in rate limiter if you want to react asynchronously when your timers go off. See [examples/js](https://github.com/ccxt-dev/ccxt/blob/master/examples/js) on how to use the built-in rate limiting long-poller in JS:

```JavaScript
const exchange = new ccxt.exchange ({ enableRateLimit: true }) // will add a delay to each next call
await exchange.fetch_balance()
await exchange.fetch_balance()  
await exchange.fetch_balance()
```

When enabled, your requests will be executed sequentially from an async queue.

**Comment by mkutny** [comment]
> When an order is placed it gets cached into this.orders property under its id.

So the cache gets initialized upon order placement. I was so sure it's a race in-between execution and fetch so totally overlooked it.

> Can you please download v1.9.95+ to see if the problem still persists? We'll stand by for more input from you.

I think I'll close it now. Liqui has quite low liquidity so sometimes it takes quite long to catch right market conditions.

> you can also try to use the built-in rate limiting poller loop if you want to call those methods asynchronously when your timers go off.

That's great that you did it. Actually, I've found it by chance today (it's not in the Manual) and was reading the code to grasp how it works.

I do poll an exchange continuously and react to incoming events by placing orders. I feel that if I don't rate limit myself during polling I'll quickly stuff a queue with fetch requests, right? So my orders won't have a chance to be executed.

**Comment by kroitor** [comment]
@mkutny 

> That's great that you did it. Actually, I've found it by chance today (it's not in the Manual) and was reading the code to grasp how it works.

It's in experimental state, that's why we didn't document it to avoid too many questions from curious users before it's done %)) 

There may be some bugs here and there, so we didn't announce it yet, but in general, it should work. There's a known bug in it - it fails if your requests get very slow, because it signs those requests upon insertion into the queue, not upon extraction of a request from a queue for sending. It should be fixed the latter way. So that each request is signed (with nonce and stuff) just before it gets sent. We actually already did most of work to fix for that and separated the `sign()` method from `request()` method, so now fixing that known bug is straightforward, we just didn't have time to rewrite it a little yet. But apart from that known bug, it should be working normally if your connection is healthy.

**Comment by mkutny** [comment]
I noticed those `sign`s scattered here and there and was wondering what are they about.

Anyway, now I think that my question about stuffing the queue was a kind of silly. I'll switch to this polling mode tomorrow. Will see how it works.

Thanks!
