### ISSUE TITLE
Ledgers query

### ISSUE THREAD

**Issue by valentinbora** [ccxt-dev/ccxt#326]
Hi.

How can I run a ledger query for Kraken for example?

Thanks!

**Comment by kroitor** [comment]
Hi, @valentinbora ! 

CCXT does not unify those methods, because they are very Kraken-specific, but the good news is that CCXT still implements all methods for Kraken, including those for querying ledger infos. So you can use their custom non-unified API for Kraken which is available in CCXT.

Afaik, you're using PHP, so, it would look like this:

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/build/ccxt.php';

date_default_timezone_set ('UTC');

// instantiate the exchange by id

$exchange = '\\ccxt\\kraken';
$exchange = new $exchange (array (
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET_KEY',
));

// get ledgers
$ledgers = $exchange->privatePostLedgers ();

// get ledger ids
$ids = array_keys ($ledgers['result']['ledger']);

// get ledger entries for ledger id
$ledger_entries = $exchange->privatePostQueryLedgers (array (
    'id' =>  $ids[0],
));

var_dump ($ledger_entries);

?>
```

I added the above example to [examples/php/kraken-query-ledgers.php](https://github.com/ccxt-dev/ccxt/blob/master/examples/php/kraken-query-ledgers.php). But when I tested it, I found a transpiler bug, and I fixed it as well, so in order for it to work, you will have to update to latest version of ccxt 1.9.155+.

I'm closing this issue for now. Feel free to reopen if needed. Also, let us know if you have any other questions or difficulties with the library. We will be happy if your report whether the above answer helped you or not. Cheers!
