### ISSUE TITLE
can exchanges override error handling?

### ISSUE THREAD

**Issue by mkutny** [ccxt-dev/ccxt#355]
Let's say I've got the following exception from Kuna:
`[Exchange Not Available Error] kuna POST https://kuna.io/api/v2/orders 400 Bad Request {"error":{"code":2002,"message":"Failed to create order. Reason: cannot lock funds (amount: 0.000138)"}} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)`

The issue is that my existing sell order was executed before I had a chance to refresh a balance. As a result, I thought I had an inventory and tried to submit one more sell order but had insufficient funds for it (as I sold all my inventory before).

If I had a chance to know that I had insufficient funds then I would have updated a balance programmatically. Unfortunately, instead of `InsufficientFunds` I caught `ExchangeNotAvailable` exception.

I see that you have a single error handler for all exchanges but it's too generic to handle all individual cases.

One approach would be to let exchange instances to override error handling. So that if I see an error to be incorrectly classified by generic handler I could handle it in exchange class.

Is there is a way for me to do it with the current `ccxt` implementation?

**Comment by kroitor** [comment]
That's a very good question, and we're actually having the same issues with them. 

So, yes, there's clearly a difference in their messaging, that's why for Kuna it failed to detect the InsufficientFunds case (it has no better way to do it other than by string search/comparison)... So, it looks like we need to redefine the request() method for Kuna to be able to catch InsufficientFund, just like it does with other BTC-e clones... until we come up with a better way to handle errors. 

By the way, we are open to all proposals, so if you can come with a design proposal to handle errors gracefully and seamlessly, then why not. We can discuss it here and, who knows, maybe we will implement it in a better and a more convenient way. If I asked you about how you would design the error overrides, what would you suggest?

**Comment by kroitor** [comment]
I'm thinking about having handleResponseErrors defined for each exchange...

**Comment by mkutny** [comment]
> If I asked you about how you would design the error overrides, what would you suggest?

I'm not fluent in JavaScript (I came here a month ago from typed languages world) so please, don't treat me rough if you find my suggestions stupid.

> I'm thinking about defining `handleErrors()` method for each exchange...

The following is based on assumption that error handling is done by `handleRestErrors()` method of the base class.

I think of empty `handleErrors(response)` method in the base class which exchange implementations could override. This `handleErrors()` is called by `handleRestErrors()` at the very beginning.

If an exchange-specific override of`handleErrors(response)` detects an error in response then it throws an appropriate exception which is then propagated to a client by the `handleRestErrors()` of the base class.

If the override does not detect an error then it returns nothing effectively resorting to the `handleRestErrors()` default error handling.

**Comment by kroitor** [comment]
Thx, @mkutny , your answer is actually very close to what we were going to implement! The base class handler will handle low-level connectivity errors, while the derived handler will be dealing with exchange-specific stuff. We also think of extending the base error class in all three languages by adding cross-portable properties, like method name, args, error message(s), error code(s), http code, all that, for more consistency and better control.

**Comment by kroitor** [comment]
This issue was closed here: https://github.com/ccxt-dev/ccxt/pull/375 in v1.9.236. Exchanges can now override default error handling in all languages. Thx for your feedback and for your amazing help! It is really important to us!
