### ISSUE TITLE
bitmex limit order error

### ISSUE THREAD

**Issue by 280wz0gz7fq1** [ccxt-dev/ccxt#368]
My code is

```
import ccxt

bitmex = ccxt.bitmex()
bitmex.apiKey = 'APIKEY'
bitmex.secret = 'SECRET'

bitmex.createLimitBuyOrder('XBTUSD', 1, 6000 )
```
error
```
urllib.error.HTTPError: HTTP Error 400: Bad Request

ccxt.errors.ExchangeNotAvailable: bitmex POST https://www.bitmex.com/api/v1/order?symbol=XBTUSD&side=Buy&orderQty=1&ordType=Limit&price=6000 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, {"error":{"message":"Nonce is not increasing. This nonce: 1508619140, last nonce: 1508586443877","name":"HTTPError"}})
```

Help me, please.

**Comment by kroitor** [comment]
Hi! Sorry, but your issue is a duplicate. It has been described in the and answered multiple times:

- https://github.com/ccxt-dev/ccxt/issues/147
- https://github.com/ccxt-dev/ccxt/search?q=nonce&type=Issues&utf8=%E2%9C%93
- https://github.com/ccxt-dev/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt-dev/ccxt/wiki/Manual#authentication
- https://github.com/ccxt-dev/ccxt/wiki/Manual#overriding-the-nonce

I'm closing this, if you don't mind.

**Comment by VangYangPao** [comment]
Hi.
How are you!
I have done real-time transaction data extract in bitmex.com.
moderndevgroup@gmail.com
Lets keep contact for world, for ourselves.
Good day 👍
