### ISSUE TITLE
Add additional fields in orders response

### ISSUE THREAD

**Issue by anandanand84** [ccxt-dev/ccxt#380]
It would be good if we add additional fields to the order response, like order validity, stop price, stop limit, post only. I know few exchange may lack few fields like post only which will be only available for maker taker exchanges. But fields like order validity and stops are common across all exchanges.

Here is an example from GDAX.
```
[
  {
    "id": "5ca4ccf3-4f14-48d4-bb4c-9799dbd06cd5",
    "info": {
      "id": "5ca4ccf3-4f14-48d4-bb4c-9799dbd06cd5",
      "price": "49.99000000",
      "size": "1.00000000",
      "product_id": "LTC-USD",
      "side": "sell",
      "stp": "dc",
      "type": "limit",
      "time_in_force": "GTC",
      "post_only": false,
      "created_at": "2017-10-23T23:54:20.499592Z",
      "fill_fees": "0.0000000000000000",
      "filled_size": "0.00000000",
      "executed_value": "0.0000000000000000",
      "status": "active",
      "settled": false,
      "stop": "loss",
      "stop_price": "50.00000000"
    },
    "timestamp": 1508802860499,
    "datetime": "2017-10-23T23:54:20.499Z",
    "status": "open",
    "symbol": "LTC/USD",
    "type": "limit",
    "side": "sell",
    "price": 49.99,
    "cost": 0,
    "amount": 1,
    "filled": 0,
    "remaining": 1
  }
]
```

**Comment by kroitor** [comment]
Hi, @anandanand84 !

We are not unifying leveraged or margin trading orders for now, because the APIs are very different in that part.

As for the validity, can you please explain what it is? Because we don't see it anywhere in the order replies from various exchanges.

**Comment by anandanand84** [comment]
@kroitor Validity is the time in force "time_in_force": "GTC", yes it is possible for an exchange to be invalid after a certain period of time, here is an example in gdax the valid values are good till cancelled, good till specified time( 1min, 1hour), immediate or cancel or fill or kill

**Comment by kroitor** [comment]
@anandanand84 oh, that validity... I got you. We will think of adding this as well, hopefully, soon.

**Comment by anandanand84** [comment]
@kroitor The more time I spend testing for the unified fields I feel like there needs to be more fields in the unified api, see for example below response from GDAX, even though stops are not supported the type of order comes as stop. I understand that comes from the upstream GDAX, but for an user who relies on ccxt may not expect stop at the type field since stops are not supported, in this case it should be Market and a separate field called stop : true if necessary

I saw an issue to move exchanges into separate files,  Is there any chance you increase your priority to move exchanges into individual files, every time I think of contributing I get lost in that one big file. I know it is very difficult to unify all possible scenario without actual trading using those api, if you can move exchanges into separate files, I can take care of all the scenario in few exchanges that I trade.

```
[
  {
    "id": "31b10883-3910-4545-890f-74ce79d35931",
    "info": {
      "id": "31b10883-3910-4545-890f-74ce79d35931",
      "price": "280.00000000",
      "size": "1.00000000",
      "product_id": "ETH-USD",
      "side": "sell",
      "stp": "dc",
      "type": "stop",
      "post_only": false,
      "created_at": "2017-10-24T14:54:47.477219Z",
      "fill_fees": "0.0000000000000000",
      "filled_size": "0.00000000",
      "executed_value": "0.0000000000000000",
      "status": "active",
      "settled": false
    },
    "timestamp": 1508856887477,
    "datetime": "2017-10-24T14:54:47.477Z",
    "status": "open",
    "symbol": "ETH/USD",
    "type": "stop",
    "side": "sell",
    "price": 280,
    "cost": 0,
    "amount": 1,
    "filled": 0,
    "remaining": 1
  }
]
```

**Comment by kroitor** [comment]
@anandanand84 

> even though stops are not supported the type of order comes as stop.

I would say, stops are supported but not unified just yet ;)
We thought it's better to leave the non-limit or non-market types as is for the user to decide what to do with it if he trades with GDAX in particular. Remapping those orders to "market" is not a vey good idea, because that would confuse the market orders with stop orders.

> I understand that comes from the upstream GDAX, but for an user who relies on ccxt may not expect stop at the type field since stops are not supported, in this case it should be Market and a separate field called stop : true if necessary

Yep, but what if I told you that the "stop" feature is only supported by approx 10-20% of all exchanges, would you still insist on raising the stop/margin/position orders up to the level of the Unified API ? I mean, in 80% of cases the orders from other exchanges would have to have that field as false, right? So, it's quite a lot of work to go through all of them. But we are making progress anyway.

> I saw an issue to move exchanges into separate files, Is there any chance you increase your priority to move exchanges into individual files, every time I think of contributing I get lost in that one big file. 

I got you, will hopefully split the big files into smaller ones very soon (really soon, maybe a day or two).

> I know it is very difficult to unify all possible scenario without actual trading using those api, if you can move exchanges into separate files, I can take care of all the scenario in few exchanges that I trade.

We are trading with our unified API, just not with the GDAX. That's why some of the exchanges may be integrated better than the other, but will integrate and unify all of them with your help. You contributions and PRs are welcome, feel free to submit them, just make sure to read the [CONTRIBUTING doc](https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md). Namely, make sure that contributions are not specific to your use case, but generic enough to make it into a consistent non-conflicting library. Thus, we need to make sure, that the added functionality covers the common subset across all exchanges, not just one or two of them. Hope you understand.

I'll update you on this, in the meantime, I would close this issue, if you don't mind. Let us know if you have any other questions or difficulties with it. Thx!
