### ISSUE TITLE
Undefined index(es) in coinmarketcap->fetch_tickers()

### ISSUE THREAD

**Issue by rubobaquero** [ccxt-dev/ccxt#385]
```
$exchange = new \ccxt\coinmarketcap();
$exchange->load_markets();
$exchange->fetch_tickers($exchange->symbols);
```
I receive lot of warnings of this kind:

Notice: Undefined index: paccoin/ in /XXXXX/ccxt.php on line 12099
PHP Notice:  Undefined index: 24h_volume_ in /XXXXX/ccxt.php on line 12055

Notice: Undefined index: 24h_volume_ in /XXXXX/ccxt.php on line 12055
PHP Notice:  Undefined index: dutch-coin/ in /XXXXX/ccxt.php on line 12099

**Comment by kroitor** [comment]
Thx for reporting! I'll take a look into it and get back to you asap.

**Comment by kroitor** [comment]
The `Undefined index: 24h_volume_ ` should be fixed as of v.1.9.242+.

As for the `Undefined index: dutch-coin/` and so on, those are caused by an improper first argument to CMC fetch_tickers. Being a unique aggregator API, It accepts a single currency in its first argument, so you should call like so:

```$exchange->fetch_tickers('USD'); // or whatever quote/base currency from CMC you need```

Let us know if you still have difficulties with it. Thx!

**Comment by rubobaquero** [comment]
Thanks kroitor. I just iterated through Exchange:$exchanges and saw the errors. Didn't know that Coinmarketcap isn't a exchange. Now I fully understand what you mean. Great job!!
